"""Add recommendations to QueryLog

Revision ID: 30e0def2c9cc
Revises: 3e1ba85dd2a9
Create Date: 2025-03-25 03:44:01.856952

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30e0def2c9cc'
down_revision = '3e1ba85dd2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###