"""fix recommendations field

Revision ID: 6d2f9f90bd5d
Revises: 30e0def2c9cc
Create Date: 2025-03-25 04:17:22.204663

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d2f9f90bd5d'
down_revision = '30e0def2c9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('querylog', sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('querylog', 'recommendations')
    # ### end Alembic commands ###