"""sync_item_product

Revision ID: b976f8fb52b7
Revises: 84f84d2e3fea
Create Date: 2025-03-24 17:46:42.913738

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b976f8fb52b7'
down_revision = '84f84d2e3fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'rating')
    op.drop_column('item', 'price')
    op.drop_column('item', 'category')
    # ### end Alembic commands ###
