"""add country

Revision ID: d4e88cc8b8a2
Revises: 04571da92845
Create Date: 2025-04-16 13:35:35.530143

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4e88cc8b8a2'
down_revision = '04571da92845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
