"""transaction handling

Revision ID: dd84432e4a24
Revises: f08a46ed8a4e
Create Date: 2025-04-01 13:37:31.171306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd84432e4a24'
down_revision = 'f08a46ed8a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pv_value', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'webinar_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'points_value')
    op.add_column('transactions', sa.Column('cash_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('pv_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('transactions', 'additional_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'points')
    op.add_column('user_product_interactions', sa.Column('pv_awarded', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('user_product_interactions', 'points_awarded')
    op.add_column('users', sa.Column('cash_balance', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('users', sa.Column('pv_balance', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'pv_balance')
    op.drop_column('users', 'cash_balance')
    op.add_column('user_product_interactions', sa.Column('points_awarded', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('user_product_interactions', 'pv_awarded')
    op.add_column('transactions', sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('transactions', 'additional_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('transactions', 'pv_amount')
    op.drop_column('transactions', 'cash_amount')
    op.add_column('products', sa.Column('points_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('products', 'webinar_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'pv_value')
    # ### end Alembic commands ###
