"""add web_link

Revision ID: f08a46ed8a4e
Revises: a9c8a619340e
Create Date: 2025-03-30 21:37:50.227677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f08a46ed8a4e'
down_revision = 'a9c8a619340e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('webinar_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'webinar_link')
    # ### end Alembic commands ###
